### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by xxcrashxx** [GaryOderNichts/alarmo_doom#4]
I've used the key_bruteforcer you made to get the aes keys successfully and I've entered them into the key.py file.  I've also downloaded a copy of doom1.wad I've found online and moved it into the data folder, but when I try to make it I get the following results

`~/Downloads/alarmo_doom-main$ make
make[1]: *** No rule to make target 'DOOM1_WAD.h', needed by 'ff.o'.  Stop.
make: *** [Makefile:160: build] Error 2
`

Is this due to an incorrect version of the doom1.wad file?  I've seen quite a few floating around out there, so I'm not sure if that's the issue or what.  I look forward to some suggestions on how to resolve this issue.

**Comment by GaryOderNichts** [comment]
The filename needs to be `doom1.wad` not `DOOM1.WAD`.

**Comment by xxcrashxx** [comment]
You're a life saver!  I guess I need to start paying attention to the case when it comes to stuff like this.  I'm glad I'm not a programmer. lol.  That totally did the trick.  I also had another error, but it was due to something else not installed.  After installing that, everything went smooth.
